### ISSUE TITLE
Fix compilation on an embedded target

### ISSUE THREAD

**Issue by fjarri** [nucypher/rust-umbral#13]
Would be useful to have the library compile for the embedded target `thumbv7em-none-eabi`. Currently there are problems with `getrandom` crate. Apparently they are fixed in `getrandom=0.2`, so we just need to wait until our `RustCrypto` dependencies pick it up.

*Update:* Even with `elliptic-curve=0.7`, there is still a dependence on 0.1 via `ecdsa -> elliptic-curve -> ff -> rand_core`. `rand_core` hasn't been updated since 2019, so hopefully it will be soon.

As soon as we have `getrandom=0.2` everywhere, we will be able to use its `rdrand` feature that will hopefully fix the compilation.

**Comment by fjarri** [comment]
`rand_core` dependency was bumped to 0.6 and `getrandom` to 0.2, so perhaps this can be fixed.

**Comment by fjarri** [comment]
It seems that my original evaluation was incorrect. It looks like there's no way to compile `getrandom()` for `thumbv7em-none-eabi`. One way to support that target would be to make RNG parameter explicit wherever it is required, and let the user obtain it by whatever means. 

Another obstacle is `hex`, which needs the `std` to support `encode`. Since we need a fixed size output, perhaps there's a heapless way to do it.

**Comment by fjarri** [comment]
Filed https://github.com/rust-random/getrandom/issues/219 to track `getrandom` support.

**Comment by josephlr** [comment]
As this is a library (rather than a binary crate), you could just defer the task of defining a custom RNG to the user of your crate (via [`register_custom_getrandom!()`](https://docs.rs/getrandom/0.2.3/getrandom/macro.register_custom_getrandom.html)). I'm not sure if there is any other way to have support (as different ArmV7 targets have different ways to get cryptographic randomness).

Looking over the [Umbral protocol doc](https://github.com/nucypher/umbral-doc/blob/master/umbral-doc.pdf) it looks like cryptographic randomness is inherent to the protocol, see section 3.2.2. So any user of this library definitely has to have _some_ way to get cryptographic randomness.

**Comment by fjarri** [comment]
Thanks for getting back to me! I agree, it seems that either asking users to register their own `getrandom()`, or even adding methods that take RNG as an argument explicitly, would be the best way to handle it.
