### ISSUE TITLE
Additional parameters to use in DEM?

### ISSUE THREAD

**Issue by fjarri** [nucypher/rust-umbral#43]
Our implementation of DEM takes additional parameters in several places:
- HKDF (`kdf()`) takes `salt` and `info`
- AEAD (`DEM`) takes `aad` (additional authenticated data)

We use DEM in two places:
- to encrypt `SecretKey` during serialization. We set `info` there to a predefined tag.
- to encrypt the plaintext in `encrypt()` (being added in #41). We use the serialized `Capsule` as `aad`.

Do we need to use other parameters too in these cases? @cygnusv , @tuxxy

**Comment by cygnusv** [comment]
> Do we need to use other parameters too in these cases?

No, I don't think it's necessary, particularly the salt parameter is not useful for us (we never start with low-entropy input).
I guess you're asking this because of this line? 
https://github.com/nucypher/rust-umbral/blob/128eb0c4c72110cccce45fadd69a1a75939d38f1/umbral-pre/src/dem.rs#L33

I think that's fine.

BTW, a side note:
> to encrypt SecretKey during serialization

I think we can/should remove this from Umbral anyway (@tuxxy wdyt?)

**Comment by fjarri** [comment]
Ok, so no HKDF info for `encrypt()` either? 

> I think we can/should remove this from Umbral anyway

It is currently removed (it was in at some point, but I did remove it after our discussion)

**Comment by cygnusv** [comment]
> Ok, so no HKDF info for `encrypt()` either?
Yeah, no need.

**Comment by fjarri** [comment]
Great, I guess I can close it then. TODOs to be removed along with other RFCs in #41
